language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t shashi2030/rick-test -f Dockerfile.dev .

script:
  - docker run -e CI=true shashi2030/rick-test npm run test